package com.example.spring_swagger.api.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

@Entity

@NoArgsConstructor
@ToString
@Table(name = "book")
public class Book implements Serializable {

    @Id
    @GeneratedValue
    @ApiModelProperty(value = "autogenerated id")
    private Integer bookId;

    @ApiModelProperty(value = "this is book name")
    private String bookName;
    @ApiModelProperty(value = "this is book price")
    private double price;

    public Integer getBookId() {
        return bookId;
    }

    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    public String getBookName() {
        return bookName;
    }

    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }
}
